### ISSUE TITLE
是否支持 租户 创建更新时间 逻辑删除 雪花id等公共字段的处理？

### ISSUE THREAD

**Issue by ghostg00** [atool/fluent-mybatis#1]
这些还是蛮需要的功能

**Comment by ghostg00** [comment]
创建更新时间 逻辑删除  找到了    创建人之类的是自己实现吗    租户和雪花id 之类的 还没看到

**Comment by ghostg00** [comment]
还有如果  entity 有父类的时候 我看生成的代码并不包含 父类的字段

**Comment by tryternity** [comment]
FluentMybatis入门介绍五：环境隔离和租户隔离




https://juejin.im/post/6895172637975117838










在 2020-11-10 10:29:28，"ghostg00" <notifications@github.com> 写道：

还有如果 entity 有父类的时候 我看生成的代码并不包含 父类的字段

**Comment by tryternity** [comment]
创建人之类的是自己实现吗
创建人自己实现， 可以参考
FluentMybatis入门介绍五：环境隔离和租户隔离
https://juejin.im/post/6895172637975117838 ， 这个不限于环境，租户，也适合创建人。


















在 2020-11-10 10:08:21，"ghostg00" <notifications@github.com> 写道：

创建更新时间 逻辑删除 找到了 创建人之类的是自己实现吗 租户和雪花id 之类的 还没看到

**Comment by tryternity** [comment]
目前不支持父类，因为Entity基本上是自动化生成的。
公共属性可以定义成接口性质













在 2020-11-10 10:29:28，"ghostg00" <notifications@github.com> 写道：

还有如果 entity 有父类的时候 我看生成的代码并不包含 父类的字段

**Comment by ghostg00** [comment]
好的  谢谢  👍
