### ISSUE TITLE
使用ERMaster 设计表，通过Maven插件自动生成DAO

### ISSUE THREAD

**Issue by zzq1314zll** [atool/fluent-mybatis#10]
Hello! 我有一个好的想法，大家可以讨论下:
ERMaster + Hibernate + QueryDSL 的这种效果
1. 先使用ERMaster 插件设计表
2. 通过Maven插件编译时，生成对应的Dao层（query 的R对象之类的）
3. 业务代码直接使用生成的代码

**Comment by tryternity** [comment]
没用过， ERMaster是不是只在eclipse下工作？

**Comment by zzq1314zll** [comment]
我可能描述的不太清楚，ERMaster只是一种数据建模工具，我们可以支持数据模型正向生成dao吗

**Comment by zzq1314zll** [comment]
@tryternity https://github.com/zzq1314zll/timi 你可以看下这个

**Comment by tryternity** [comment]
暂无计划支持
