### ISSUE TITLE
Can fluent mybatis print SQL in log？

### ISSUE THREAD

**Issue by 814196912** [atool/fluent-mybatis#11]
Hey。I am studying fluent mybatis.I wan to print sql in log.But I can't find the introduction in the "fluent mybatis docs ".What should I do?

**Comment by tryternity** [comment]
u can use mybatis log. 
Fluent mybatis does not change the mechanism of mybatis, but only enhances the SQL encapsulation syntax. The original functions of mybatis can be used as usual

**Comment by 814196912** [comment]
> u can use mybatis log.
> Fluent mybatis does not change the mechanism of mybatis, but only enhances the SQL encapsulation syntax. The original functions of mybatis can be used as usual

Thanks.I have resolved my problem
