### ISSUE TITLE
自定义查询语句时能否提供分页功能？

### ISSUE THREAD

**Issue by abcbuzhiming** [atool/fluent-mybatis#15]
我阅读了文档，查阅了自定义查询语句的章节，按我的理解，自定义语句时似乎分页部分也必须自己处理，能否提供一个插件或者别的功能，能让自定义查询时也能方便的使用分页功能呢？

**Comment by tryternity** [comment]
自定义的语句无法识别 limit内容，除非做sql语句的语法解析。
sql语句的语法解析，可以使用mybatis的插件PageHelper
