### ISSUE TITLE
请问fluent mybatis 如何在生成的实体类中加入临时字段

### ISSUE THREAD

**Issue by 814196912** [atool/fluent-mybatis#18]
当我在实体类加个临时属性时，查询就会把这个手动添加的属性加入查询

![Snipaste_2021-09-18_23-56-46](https://user-images.githubusercontent.com/38856046/133894858-e55aa6bf-e168-471b-ad8b-f9a98d8f762e.png)
![Snipaste_2021-09-18_23-57-27](https://user-images.githubusercontent.com/38856046/133894873-f524a893-033f-4b41-85f2-7d726d7cf6c1.png)

**Comment by tryternity** [comment]
暂时没有办法，你只有继承Entity类，或者写接口方式
