### ISSUE TITLE
支持生成类名后缀名自定义配置

### ISSUE THREAD

**Issue by fyobe** [atool/fluent-mybatis#7]
希望支持阿里规约的后缀名命名规范，包括Entity和DAO， 可以全局配置，不需要Entity每个类上单独配置。最好在生成代码的时候就可以。

**Comment by tryternity** [comment]
没看明白，现在生成的代码，就是以Entity，Dao结尾的，没有每个类配置呢。

**Comment by tryternity** [comment]
v1.5.10已支持实体类生成的后缀名称定义
https://gitee.com/fluent-mybatis/fluent-mybatis/issues/I3VIK8
